name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  js:
    uses: unundoTeam/.github/.github/workflows/node-verify.yml@main
    with:
      node_version: "22"
      package_manager: pnpm
      install_command: pnpm install --no-frozen-lockfile
      lint_command: pnpm lint
      test_command: pnpm test
