name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  js:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
      - run: corepack enable
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm lint
      - run: pnpm test
